// The single knowledge source: the KB files in kb/manifest.json joined into one program, plus
// facts generated from what the repository already records, versioned by content hash.
// Shared by the web server and the MCP server, so both always see the same KB.

import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const MANIFEST = join(ROOT, "kb", "manifest.json");
const PACKAGE = join(ROOT, "package.json");

export interface KbFile {
  name: string;
  lines: number;
  sha: string;
  modified: number;
}

export interface Kb {
  version: string;
  loadedAt: number;
  files: KbFile[];
  program: string;
}

const sha = (text: string, n: number) => createHash("sha1").update(text).digest("hex").slice(0, n);

export async function loadKb(): Promise<Kb> {
  const { sources } = JSON.parse(await readFile(MANIFEST, "utf8")) as { sources: string[] };
  const files: KbFile[] = [];
  const parts: string[] = [];
  for (const rel of sources) {
    const path = join(ROOT, rel);
    let text = await readFile(path, "utf8");
    if (!text.endsWith("\n")) text += "\n";
    files.push({
      name: rel,
      lines: text.split("\n").length - 1,
      sha: sha(text, 10),
      modified: Math.floor((await stat(path)).mtimeMs / 1000),
    });
    parts.push(`% ===== ${rel} =====\n${text}`);
  }
  parts.push(await generatedFacts(sources));
  const program = parts.join("\n");
  return { version: sha(program, 12), loadedAt: Math.floor(Date.now() / 1000), files, program };
}

const atom = (s: string) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

/** Directories whose TypeScript files get a file_summary/2 (KB files always do). */
const SUMMARY_DIRS = ["", "lib", "public", "scripts"];

/**
 * Facts the repository already records, so nobody restates them (see kb/system.pl):
 * kb_file/2 from the manifest; package_version/2, engine_requirement/2, npm_script/2 and
 * npm_script_file/2 from package.json; file_summary/2 from each file's header comment.
 */
async function generatedFacts(sources: string[]): Promise<string> {
  type Package = { dependencies?: Record<string, string>; devDependencies?: Record<string, string>;
    engines?: Record<string, string>; scripts?: Record<string, string> };
  const pkg = JSON.parse(await readFile(PACKAGE, "utf8")) as Package;
  const packages = { ...pkg.dependencies, ...pkg.devDependencies };
  const scripts = Object.entries(pkg.scripts ?? {});
  const summaries: string[] = [];
  for (const file of await describedFiles(sources)) {
    const summary = headerSummary(await readFile(join(ROOT, file), "utf8"));
    if (summary) summaries.push(`file_summary(${atom(file)}, ${atom(summary)}).`);
  }
  return [
    "% ===== generated by lib/kb-source.ts from kb/manifest.json, package.json and file headers =====",
    ...sources.map((f) => `kb_file(knowledge_base, ${atom(f)}).`),
    ...Object.entries(packages).map(([name, version]) => `package_version(${atom(name)}, ${atom(version)}).`),
    ...Object.entries(pkg.engines ?? {}).map(([engine, range]) => `engine_requirement(${atom(engine)}, ${atom(range)}).`),
    ...scripts.map(([name, command]) => `npm_script(${atom(name)}, ${atom(command)}).`),
    ...scripts.flatMap(([name, command]) =>
      command.split(/\s+/).filter((w) => /\.(ts|js)$/.test(w)).map((file) => `npm_script_file(${atom(name)}, ${atom(file)}).`)),
    ...summaries,
    "",
  ].join("\n");
}

async function describedFiles(sources: string[]): Promise<string[]> {
  const files = new Set(sources);
  for (const dir of SUMMARY_DIRS) {
    for (const name of (await readdir(join(ROOT, dir))).sort()) {
      if (/^[^.].*\.ts$/.test(name)) files.add(dir ? `${dir}/${name}` : name);
    }
  }
  return [...files];
}

/** First sentence of a file's leading comment, without "name.pl — " and the full stop. */
export function headerSummary(text: string): string | null {
  const lines: string[] = [];
  for (const line of text.split("\n")) {
    const m = line.match(/^\s*(?:%|\/\/)\s?(.*)$/);
    if (!m) break;
    const content = m[1].trim();
    if (!content) {
      if (lines.length) break;
      continue;
    }
    lines.push(content);
  }
  if (!lines.length) return null;
  const joined = lines.join(" ").replace(/^[\w./-]+\s+—\s+/, "");
  const end = joined.search(/[.!?](\s|$)/);
  return end >= 0 ? joined.slice(0, end) : joined;
}
