// The single knowledge source: the KB files in kb/manifest.json joined into one program, plus
// facts generated from what the repository already records, versioned by content hash.
// Shared by the web server and the MCP server, so both always see the same KB.

import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const MANIFEST = join(ROOT, "kb", "manifest.json");
const PACKAGE = join(ROOT, "package.json");

export interface KbFile {
  name: string;
  lines: number;
  sha: string;
  modified: number;
}

export interface Kb {
  version: string;
  loadedAt: number;
  files: KbFile[];
  program: string;
}

const sha = (text: string, n: number) => createHash("sha1").update(text).digest("hex").slice(0, n);

export async function loadKb(): Promise<Kb> {
  const { sources } = JSON.parse(await readFile(MANIFEST, "utf8")) as { sources: string[] };
  const files: KbFile[] = [];
  const parts: string[] = [];
  for (const rel of sources) {
    const path = join(ROOT, rel);
    let text = await readFile(path, "utf8");
    if (!text.endsWith("\n")) text += "\n";
    files.push({
      name: rel,
      lines: text.split("\n").length - 1,
      sha: sha(text, 10),
      modified: Math.floor((await stat(path)).mtimeMs / 1000),
    });
    parts.push(`% ===== ${rel} =====\n${text}`);
  }
  parts.push(await generatedFacts(sources));
  const program = parts.join("\n");
  return { version: sha(program, 12), loadedAt: Math.floor(Date.now() / 1000), files, program };
}

const atom = (s: string) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n").replace(/\t/g, "\\t")}'`;

/** Files that get a file_summary/2 besides the KB files: TypeScript, and ASP programs in kb/. */
const SUMMARY_FILES: [dir: string, pattern: RegExp][] = [
  ["", /^[^.].*\.ts$/], ["lib", /^[^.].*\.ts$/], ["public", /^[^.].*\.ts$/], ["scripts", /^[^.].*\.ts$/], ["kb", /^[^.].*\.lp$/],
];

/**
 * Facts the repository already records, so nobody restates them (see kb/system.pl):
 * kb_file/2 from the manifest; package_version/2, engine_requirement/2, npm_script/2 and
 * npm_script_file/2 from package.json; file_summary/2 from each file's header comment.
 * clause_source/6 holds each fact and explained rule as written, for technical readers. Each generated
 * predicate is also listed in generated_predicate/2, so the audit counts these as free.
 */
async function generatedFacts(sources: string[]): Promise<string> {
  type Package = { dependencies?: Record<string, string>; devDependencies?: Record<string, string>;
    engines?: Record<string, string>; scripts?: Record<string, string> };
  const pkg = JSON.parse(await readFile(PACKAGE, "utf8")) as Package;
  const facts: string[] = [];
  const generated = new Map<string, number>();
  const fact = (name: string, ...args: string[]) => {
    generated.set(name, args.length);
    facts.push(`${name}(${args.map(atom).join(", ")}).`);
  };
  for (const f of sources) fact("kb_file", "knowledge_base", f);
  for (const [name, version] of Object.entries({ ...pkg.dependencies, ...pkg.devDependencies })) fact("package_version", name, version);
  for (const [engine, range] of Object.entries(pkg.engines ?? {})) fact("engine_requirement", engine, range);
  const scripts = Object.entries(pkg.scripts ?? {});
  for (const [name, command] of scripts) fact("npm_script", name, command);
  for (const [name, command] of scripts) {
    for (const file of command.split(/\s+/).filter((w) => /\.(ts|js)$/.test(w))) fact("npm_script_file", name, file);
  }
  for (const file of await describedFiles(sources)) {
    const summary = headerSummary(await readFile(join(ROOT, file), "utf8"));
    if (summary) fact("file_summary", file, summary);
  }
  // Facts and explained rules (those declared dynamic, practice dynamic_rules) as written,
  // numbered like clause/2 numbers them across the whole program.
  const texts = await Promise.all(sources.map((f) => readFile(join(ROOT, f), "utf8")));
  const dynamic = new Set(texts.flatMap((t) => [...t.matchAll(/^:-\s*dynamic\(?\s*([a-z]\w*\/\d+)/gm)].map((m) => m[1])));
  const seen = new Map<string, number>();
  for (const [k, file] of sources.entries()) {
    for (const c of sourceClauses(texts[k])) {
      const key = `${c.name}/${c.arity}`;
      const index = (seen.get(key) ?? 0) + 1;
      seen.set(key, index);
      if (!c.rule || dynamic.has(key)) {
        generated.set("clause_source", 6);
        facts.push(`clause_source(${c.name}, ${c.arity}, ${index}, ${atom(file)}, ${c.line}, ${atom(c.text)}).`);
      }
    }
  }
  return [
    "% ===== generated by lib/kb-source.ts from kb/manifest.json, package.json and file headers =====",
    ...facts,
    ...[...generated].map(([name, arity]) => `generated_predicate(${name}, ${arity}).`),
    "",
  ].join("\n");
}

async function describedFiles(sources: string[]): Promise<string[]> {
  const files = new Set(sources);
  for (const [dir, pattern] of SUMMARY_FILES) {
    for (const name of (await readdir(join(ROOT, dir))).sort()) {
      if (pattern.test(name)) files.add(dir ? `${dir}/${name}` : name);
    }
  }
  return [...files];
}

export interface SourceClause { name: string; arity: number; line: number; rule: boolean; text: string }

const SYMBOL_CHARS = new Set("+-*/\\^<>=~:.?@#&$");

/**
 * The clauses of a Prolog file as written: head name and arity, first line, whether it
 * is a rule, and its text with the comment lines directly above it. Directives are
 * skipped. Enough of Prolog's syntax to split clauses: quotes, 0'c, comments, end dots.
 */
export function sourceClauses(text: string): SourceClause[] {
  const out: SourceClause[] = [];
  const lineAt = (i: number) => text.slice(0, i).split("\n").length;
  const n = text.length;
  let i = 0;
  let comment: { start: number; lastLine: number } | null = null;
  const skipQuoted = (q: string) => {
    for (i++; i < n; i++) {
      if (text[i] === "\\") { i++; continue; }
      if (text[i] === q) {
        if (text[i + 1] === q) { i++; continue; }
        return;
      }
    }
  };
  while (i < n) {
    const c = text[i];
    if (/\s/.test(c)) { i++; continue; }
    if (c === "%") {
      // Only a comment on a line of its own describes the clause below; a trailing one does not.
      const line = lineAt(i);
      const lineStart = text.lastIndexOf("\n", i) + 1;
      if (text.slice(lineStart, i).trim()) comment = null;
      else if (!comment || comment.lastLine !== line - 1) comment = { start: lineStart, lastLine: line };
      else comment.lastLine = line;
      const eol = text.indexOf("\n", i);
      i = eol < 0 ? n : eol;
      continue;
    }
    if (c === "/" && text[i + 1] === "*") { const e = text.indexOf("*/", i + 2); i = e < 0 ? n : e + 2; continue; }
    // A clause starts here and ends at a dot followed by layout.
    const start = i;
    const line = lineAt(start);
    let end = n;
    let body = -1;
    let depth = 0;
    for (; i < n; i++) {
      const ch = text[i];
      if (ch === "'" || ch === '"' || ch === "`") {
        if (ch === "'" && text[i - 1] === "0" && !/[A-Za-z0-9_]/.test(text[i - 2] ?? "")) { i += text[i + 1] === "\\" ? 2 : 1; continue; }
        skipQuoted(ch); continue;
      }
      if (ch === "%") { const eol = text.indexOf("\n", i); i = eol < 0 ? n : eol; continue; }
      if (ch === "(" || ch === "[" || ch === "{") depth++;
      else if (ch === ")" || ch === "]" || ch === "}") depth--;
      else if (depth === 0 && ch === ":" && text[i + 1] === "-" && body < 0) body = i;
      else if (ch === "." && (i + 1 >= n || /[\s%]/.test(text[i + 1])) && !SYMBOL_CHARS.has(text[i - 1])) { end = i + 1; break; }
    }
    // A comment after the dot on the same line is part of the clause as written.
    const rest = text.slice(end).match(/^[ \t]*%[^\n]*/);
    if (rest) end += rest[0].length;
    i = end;
    const clause = text.slice(start, end);
    const attached = comment && comment.lastLine === line - 1
      ? text.slice(comment.start, start).split("\n").filter((l) => !/^\s*%\s*---/.test(l)).join("\n")
      : "";
    comment = null;
    if (clause.startsWith(":-")) continue;
    const head = clause.match(/^([a-z][A-Za-z0-9_]*|'(?:[^'\\]|\\.|'')*')(\()?/);
    if (!head) continue;
    out.push({ name: head[1], arity: head[2] ? headArity(clause, head[0].length) : 0, line, rule: body >= 0, text: attached + clause });
  }
  return out;
}

/** Arguments of the head whose "(" ends at `from`: top-level commas until the matching ")". */
function headArity(clause: string, from: number): number {
  let depth = 1;
  let commas = 0;
  for (let i = from; i < clause.length && depth > 0; i++) {
    const ch = clause[i];
    if (ch === "'" || ch === '"') {
      for (i++; i < clause.length && clause[i] !== ch; i++) if (clause[i] === "\\") i++;
    } else if (ch === "(" || ch === "[" || ch === "{") depth++;
    else if (ch === ")" || ch === "]" || ch === "}") depth--;
    else if (ch === "," && depth === 1) commas++;
  }
  return commas + 1;
}

/** First sentence of a file's leading comment, without "name.pl — " and the full stop. */
export function headerSummary(text: string): string | null {
  const lines: string[] = [];
  for (const line of text.split("\n")) {
    const m = line.match(/^\s*(?:%|\/\/)\s?(.*)$/);
    if (!m) break;
    const content = m[1].trim();
    if (!content) {
      if (lines.length) break;
      continue;
    }
    lines.push(content);
  }
  if (!lines.length) return null;
  const joined = lines.join(" ").replace(/^[\w./-]+\s+—\s+/, "");
  const end = joined.search(/[.!?](\s|$)/);
  return end >= 0 ? joined.slice(0, end) : joined;
}
