% lexicon.pl — the primitive vocabulary every label and explanation is built from.
%
% Nothing here is a finished sentence. explain.pl composes sentences, edge
% labels, rule descriptions and calculations from these words, so adding a
% relation usually needs at most one noun/2 or verb/2 line (atoms like
% wallet_exposure are humanised to "wallet exposure" by default).

% The primitives this file defines; the audit counts their entries as vocabulary.
primitive(noun, 2).
primitive(verb, 2).
primitive(subject, 2).
primitive(object, 2).
primitive(arg_verb, 3).
primitive(unit, 2).
primitive(unit_word, 2).
primitive(bare, 1).
primitive(flag, 3).
primitive(op_word, 2).
primitive(op_symbol, 2).
primitive(op_precedence, 2).
primitive(action, 2).
primitive(connective, 2).
primitive(plural, 1).

% noun(Concept, Phrase) — what a concept, attribute, type, role or user is called.
% For a predicate P(S, O), it names O: noun(repo, team).
noun(requires, requirement).
noun(depends_on, dependency).
noun(needs_setup, 'environment setup').
noun(env_setup, 'environment setup').
noun(own_repository, 'the service''s own repository').
noun(member_of, team).
noun(belongs_to, organisation).
noun(address, 'email address').
noun(product_domain, domain).
noun(email_role, role).
noun(email_provider, provider).
noun(google_workspace, 'Google Workspace').
noun(system, 'System').
noun(knowledge_explorer, 'Liquidity House Knowledge Explorer').
noun(readme_overview, 'Overview').
noun(readme_components, 'Components').
noun(readme_running, 'Running it').
noun(readme_access, 'Who sees what').
noun(readme_knowledge, 'Knowledge files').
noun(readme_rest, 'REST API').
noun(readme_mcp, 'MCP server for AI agents').
noun(readme_explorer, 'Using the explorer').
noun(readme_practices, 'Working on the knowledge base').
noun(npm_script, 'package script').
noun(npm_script_file, file).
noun(runs_component, component).
noun(described_as, description).
noun(file_summary, summary).
noun(engine_requirement, 'required version').
noun(identity_setting, setting).
noun(compression, 'compression template').
noun(api_docs_path, 'API docs path').
noun(knowledge_kind, 'kind of knowledge').
noun(similar_name, 'similar name, different thing').
noun(generated_origin, 'taken from').
noun(generator_code, 'generated by').
noun(api_reference, 'API reference').
noun(class_value, 'class-implied value').
noun(identity, 'same pairs').
noun(inverse, 'reversed pairs').
noun(subsumes, 'already held elsewhere').
noun(chain, 'two-step path').
noun(interpolation, 'shared text template').
noun(shared_conjunction, 'repeated conditions').
noun(lexicon_default, 'default word').
noun(dead_clause, 'unused rule clause').
noun(per_user_settings, 'per-user settings').
noun(ui, 'user interface').
noun(knowledge, 'knowledge base').
noun(tool, 'MCP tool').
noun(request, 'knowledge request').
noun(text, description).
noun(node, 'Node.js').
noun(browser, 'the browser').
noun(uses, part).
noun(relies_on, dependency).
noun(access, feature).
noun(role_feature, feature).
noun(can_call, endpoint).
noun(answers_with, request).
noun(mcp_tool, request).
noun(served_by, server).
noun(same_answer, 'MCP tool').
noun(package_version, version).
noun(runs_on, runtime).
noun(ggr_90d, '90-day gross gaming revenue').
noun(net_deposits, 'net player deposits').
noun(dau, 'daily active user count').
noun(exposure_warning, 'exposure level').
noun(risk_weight, value).
noun(weight, 'risk weight').
noun(step, 'onboarding step').
noun(url, link).
noun(platform, 'RiskX platform').
noun(workspace, 'Slack workspace').
noun(channel, 'Slack channel').
noun(identifier, 'ID').
noun(jira_project, 'Jira project').
noun(repo, team).
noun(sibling_repo, 'other repository').
noun(github_account, 'GitHub account').
noun(slack_channel, 'Slack channel').
noun(slack_client_id, 'Slack client ID').
noun(slack_channel_id, 'Slack channel ID').
noun(jira_site, 'Jira site').
noun(jira_board, 'Jira board').
noun(deployed_on, cluster).
noun(personal_email, 'your personal email').
noun(work_email, 'your work email').
noun(team_email, 'your team email').
noun(admin, administrator).
noun(dominic, 'Dominic, Head of Risk').
noun(adam, 'Adam, Software Engineer').

% plural(Concept) — takes "are" instead of "is".
plural(net_deposits).

% subject(Relation, Phrase) — what a relation's subjects are called in rules, when
% its facts mix kinds of subject (otherwise it is read from the first fact).
:- dynamic(subject/2).
subject(component, component).
subject(uses, component).
subject(role_feature, role).
subject(access, endpoint).
subject(answers_with, endpoint).
subject(mcp_tool, 'MCP tool').
subject(source_file, component).
subject(npm_script_file, 'package script').

% object(Relation, Phrase) — what a relation's object is called in rules, when its
% noun/2 already names something else (operator/2's noun is the operator type).
:- dynamic(object/2).
object(operator, status).
object(npm_script, command).
object(component, kind).

% verb(Relation, Phrase) — relations read as "Subject Verb Object".
% Predicates without a verb are attributes: "the <noun> of Subject is Value".
verb(onboarding, includes).
verb(part_of, 'is part of').
verb(builds, builds).
verb(member_of, 'is a member of').
verb(belongs_to, 'belongs to').
verb(mailbox, provides).
verb(managed_by, 'is managed by').
verb(invites, 'invites you to').
verb(works_as, 'works as').
verb(reachable_in, 'is reachable in').
verb(repo, 'belongs to').
verb(sibling_repo, 'is a sibling of').
verb(invitation_sent_to, 'is joined via an invitation to').
verb(signs_in_with, 'is reached with').
verb(dashboard, 'is shown on').
verb(deployed_on, 'is deployed on').
verb(riskx, 'flows into').
verb(data_source, 'pulls data from').
verb(monitors, monitors).
verb(in_portfolio, 'is part of').
verb(operator, 'has status').
verb(slack_channel, contains).
verb(requires, requires).
verb(component, 'is of kind').
verb(executes_in, 'runs in').
verb(kb_file, 'is made of').
verb(uses, uses).
verb(relies_on, 'relies on').
verb(access, requires).
verb(role_feature, has).
verb(can_call, 'can call').
verb(answers_with, 'answers with').
verb(mcp_tool, 'answers with').
verb(served_by, 'is served by').
verb(same_answer, 'gives the same answer as').
verb(runs_on, 'runs on').
verb(npm_script, runs).
verb(npm_script_file, runs).
verb(runs_component, starts).
verb(registered_in, 'is registered for Claude Code in').
verb(offers, offers).
verb(depends_on, 'depends on').
verb(needs_setup, needs).

% arg_verb(Relation, ArgN, Phrase) — how extra arguments of n-ary facts attach.
:- dynamic(arg_verb/3).

% unit(Attribute, Unit) and how a unit is written after a number.
unit(ggr_90d, usd).
unit(net_deposits, usd).
unit(wallet_exposure, usd).
unit(soft_credit_limit, usd).
unit(daily_allowance, usd).
unit(dau, count).
unit_word(usd, 'USD').

% bare(Type) — entities of this type are written without "<type> '...'".
bare(url).
bare(value).
bare(status).
bare(identifier).
bare(account).
bare(domain).
bare(email).
bare(address).
bare(kind).
bare(runtime).
bare(text).
bare(concept).

% flag(Attribute, Value, Severity) — values that deserve attention.
flag(exposure_warning, high, warning).

% Operators, as words and symbols.
op_word(>, 'is greater than').
op_word(<, 'is less than').
op_word(>=, 'is at least').
op_word(=<, 'is at most').
op_word(=:=, equals).
op_word(=\=, 'differs from').
op_word(\==, 'differs from').
op_symbol(+, '+').
op_symbol(-, '−').
op_symbol(*, '×').
op_symbol(/, '÷').
op_precedence(+, 1).
op_precedence(-, 1).
op_precedence(*, 2).
op_precedence(/, 2).

% action(Type, Verb) — what you do to satisfy a requirement of that type.
action(service, clone).
action(repository, clone).
action(env_setup, 'set up').
action(data_source, 'get access to').
action(dashboard, 'get access to').

% Connectives used when joining phrases.
connective(and, and).
connective(when, when).
connective(calculated, 'Calculated:').
connective(checked, 'Checked:').
connective(built, 'Built:').
connective(from, from).
connective(ready, 'has everything needed to work on').
connective(still_needs, 'still needs to').
connective(before_working_on, 'before working on').
connective(unrecorded, 'no requirements are recorded for').
connective(exists, exists).
connective(definite, the).
connective(organised_in, 'its knowledge is organised in these domains:').
connective(access_rule, 'who may call each endpoint follows one rule:').
connective(sample_data, 'illustrative sample data:').
connective(none, '—').
