% lexicon.pl — the primitive vocabulary every label and explanation is built from.
%
% Nothing here is a finished sentence. explain.pl composes sentences, edge
% labels, rule descriptions and calculations from these words, so adding a
% relation usually needs at most one noun/2 or verb/2 line (atoms like
% wallet_exposure are humanised to "wallet exposure" by default). This file holds
% the engine's own words; each knowledge pack adds its words in its vocabulary.pl.

% The primitives this file defines; the audit counts their entries as vocabulary.
primitive(noun, 2).
primitive(verb, 2).
primitive(subject, 2).
primitive(object, 2).
primitive(arg_verb, 3).
primitive(unit, 2).
primitive(unit_word, 2).
primitive(bare, 1).
primitive(flag, 3).
primitive(op_word, 2).
primitive(op_symbol, 2).
primitive(op_precedence, 2).
primitive(action, 2).
primitive(connective, 2).
primitive(plural, 1).

% noun(Concept, Phrase) — what a concept, attribute, type, role or user is called.
% For a predicate P(S, O), it names O: noun(repo, team).
noun(own_repository, 'the service''s own repository').
noun(compression, 'compression template').
noun(knowledge_kind, 'kind of knowledge').
noun(similar_name, 'similar name, different thing').
noun(generated_origin, 'taken from').
noun(generator_code, 'generated by').
noun(generated_from, 'read from').
noun(made_by, 'made by').
noun(made_with, 'made again by').
noun(agent_task, 'agent steps').
noun(class_value, 'class-implied value').
noun(identity, 'same pairs').
noun(inverse, 'reversed pairs').
noun(subsumes, 'already held elsewhere').
noun(chain, 'two-step path').
noun(interpolation, 'shared text template').
noun(shared_conjunction, 'repeated conditions').
noun(lexicon_default, 'default word').
noun(dead_clause, 'unused rule clause').
noun(text, description).
noun(role_feature, feature).
noun(url, link).
% The kinds of knowledge go by their standard names (kb/core.pl also_called/3 lists the others).
noun(stated, asserted).
noun(derived, inferred).
noun(generated, extracted).
noun(imported, ingested).
noun(local, draft).
noun(datalog, 'Datalog').
noun(logic, logic).
noun(data_integration, 'data integration').
noun(version_control, 'version control terms').
noun(this_knowledge_base, 'this knowledge base''s own files').
noun(warning, 'needs attention').
noun(explorer, 'the explorer').
noun(mcp, 'an agent over MCP').

% plural(Concept) — takes "are" instead of "is".
:- dynamic(plural/1).

% subject(Relation, Phrase) — what a relation's subjects are called in rules, when
% its facts mix kinds of subject (otherwise it is read from the first fact).
:- dynamic(subject/2).
subject(role_feature, role).

% object(Relation, Phrase) — what a relation's object is called in rules, when its
% noun/2 already names something else (operator/2's noun is the operator type).
:- dynamic(object/2).

% verb(Relation, Phrase) — relations read as "Subject Verb Object".
% Predicates without a verb are attributes: "the <noun> of Subject is Value".
verb(role_feature, has).

% arg_verb(Relation, ArgN, Phrase) — how extra arguments of n-ary facts attach.
:- dynamic(arg_verb/3).

% unit(Attribute, Unit) and how a unit is written after a number.
:- dynamic(unit/2).
:- dynamic(unit_word/2).

% bare(Type) — entities of this type are written without "<type> '...'".
bare(url).
bare(value).
bare(text).
bare(concept).

% flag(Attribute, Value, Severity) — values that deserve attention.
:- dynamic(flag/3).

% Operators, as words and symbols.
op_word(>, 'is greater than').
op_word(<, 'is less than').
op_word(>=, 'is at least').
op_word(=<, 'is at most').
op_word(=:=, equals).
op_word(=\=, 'differs from').
op_word(\==, 'differs from').
op_symbol(+, '+').
op_symbol(-, '−').
op_symbol(*, '×').
op_symbol(/, '÷').
op_precedence(+, 1).
op_precedence(-, 1).
op_precedence(*, 2).
op_precedence(/, 2).

% action(Type, Verb) — what you do to satisfy a requirement of that type.
:- dynamic(action/2).

% Connectives used when joining phrases.
connective(and, and).
connective(when, when).
connective(calculated, 'Calculated:').
connective(checked, 'Checked:').
connective(built, 'Built:').
connective(from, from).
connective(ready, 'has everything needed to work on').
connective(still_needs, 'still needs to').
connective(before_working_on, 'before working on').
connective(unrecorded, 'no requirements are recorded for').
connective(exists, exists).
connective(definite, the).
connective(none, '—').
connective(also_called, 'also called').
connective(in_field, in).
connective(mdl_terms, 'in minimum description length terms').
connective(model, 'it is part of the model, so L(model) counts it').
connective(data, 'it is the data given the model, L(data | model): what the model leaves unexplained and has to be written out').
connective(explained, 'it is data the model explains, free once the rules are there, so it counts only in the comparison without rules').
connective(explained_by_code, 'it is data explained by the code that reads it, which L(model) counts under implementations').
connective(added_by, 'added by').
connective(removed_by, 'removed by').
connective(through, through).
connective(read_from, 'read from').
connective(replacing, replacing).
connective(pasted, pasted).
