// Composes README.md from the knowledge base: every heading, sentence and table cell comes from kb/*.pl.
//
// The sections and their content are knowledge (kb/readme.pl reading kb/system.pl, the schema
// and the lexicon); this script only renders them as Markdown.
//
// Run: npm run readme          (writes README.md)
//      npm run readme:check    (exits 1 when README.md is out of date)

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { current } from "../lib/kb-service.ts";

type Block =
  | { kind: "para"; text: string }
  | { kind: "bullets"; items: string[] }
  | { kind: "table"; columns: string[]; rows: string[][] }
  | { kind: "code"; lang: string; text: string }
  | { kind: "graph"; nodes: { id: string; label: string }[]; edges: { from: string; to: string }[] };

interface Readme {
  title: string;
  sections: { id: string; heading: string; ok: boolean; blocks: Block[] }[];
}

const README = join(import.meta.dirname, "..", "README.md");

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function render(block: Block): string {
  switch (block.kind) {
    case "para":
      return block.text;
    case "bullets":
      return block.items.map((i) => `- ${i}`).join("\n");
    case "table":
      return [
        `| ${block.columns.map(cell).join(" | ")} |`,
        `| ${block.columns.map(() => "---").join(" | ")} |`,
        ...block.rows.map((r) => `| ${r.map(cell).join(" | ")} |`),
      ].join("\n");
    case "code":
      return `\`\`\`${block.lang}\n${block.text}\n\`\`\``;
    case "graph": {
      // Mermaid ids must be plain; labels carry the real names.
      const id = new Map(block.nodes.map((n, i) => [n.id, `n${i}`]));
      return [
        "```mermaid",
        "graph LR",
        ...block.nodes.map((n) => `  ${id.get(n.id)}["${n.label.replace(/"/g, "'")}"]`),
        ...block.edges.map((e) => `  ${id.get(e.from)} --> ${id.get(e.to)}`),
        "```",
      ].join("\n");
    }
  }
}

const { engine } = await current();
const doc = await engine.api<Readme>("readme");

const failed = doc.sections.filter((s) => !s.ok).map((s) => s.id);
if (failed.length) {
  console.error(`The knowledge base could not compose: ${failed.join(", ")}`);
  process.exit(1);
}

const markdown = [
  "<!-- Generated by `npm run readme` from the knowledge base. Change kb/*.pl, file headers or package.json, not this file. -->",
  `# ${doc.title}`,
  ...doc.sections.map((s) => [`## ${s.heading}`, ...s.blocks.map(render)].join("\n\n")),
].join("\n\n") + "\n";

if (process.argv.includes("--check")) {
  const existing = await readFile(README, "utf8").catch(() => "");
  if (existing !== markdown) {
    console.error("README.md is out of date: run npm run readme");
    process.exit(1);
  }
  console.log("README.md is up to date");
} else {
  await writeFile(README, markdown);
  console.log(`Wrote README.md (${doc.sections.length} sections)`);
}
